ConfigInst: true
InjectMode: dynamicInstance
Instances:
- IDENTITY = 2
- MUL = 1
- ADD = 1
- SUB = 1
- POW = 1
- RANK = 1
- RANGE = 1
- SUM = 1
- REALDIV = 1
Ops: null
ScalarFaultType: None
TensorFaultType: bitFlip-element
